// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ACard: typeof import('ant-design-vue/es')['Card']
    Affix: typeof import('./src/components/Affix.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    Artist: typeof import('./src/views/Hall/components/Artist.vue')['default']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Category: typeof import('./src/views/Hall/components/Category.vue')['default']
    Dt: typeof import('./src/views/Hall/components/Dt.vue')['default']
    Hall: typeof import('./src/views/Hall/index.vue')['default']
    IconPark: typeof import('./src/components/IconPark.vue')['default']
    Layout: typeof import('./src/views/Layout/index.vue')['default']
    Like: typeof import('./src/views/Like/index.vue')['default']
    Local: typeof import('./src/views/Local/index.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    MySider: typeof import('./src/components/MySider.vue')['default']
    Pay: typeof import('./src/views/Pay/index.vue')['default']
    Picked: typeof import('./src/views/Hall/components/Picked.vue')['default']
    PlayList: typeof import('./src/views/PlayList/index.vue')['default']
    Plays: typeof import('./src/views/Plays/index.vue')['default']
    Radio: typeof import('./src/views/Radio/index.vue')['default']
    Recommend: typeof import('./src/views/Recommend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/SearchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/SearchSuggest.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    Toplist: typeof import('./src/views/Hall/components/Toplist.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    Video: typeof import('./src/views/Video/index.vue')['default']
    Zj: typeof import('./src/views/Hall/components/Zj.vue')['default']
  }
}
